# Generated by Django 2.2.1 on 2019-05-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('local', models.TextField()),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_participantes', models.IntegerField()),
            ],
        ),
    ]
