# Generated by Django 2.2.1 on 2019-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='eventos',
            field=models.ManyToManyField(blank=True, null=True, to='eventos.Evento'),
        ),
    ]
